name: valid_dart_project
description: Valid Dart project
version: 1.0.0
homepage: https://github.com/fartem/flutter_rb/tree/master/test_assets/valid_dart_project

dev_dependencies:
  effective_dart: ^1.3.0
  dart_enum_to_string_check: ^0.6.2
